services:
  backend:
    build: ./backend
    ports:
      - '8050:8085'
    volumes:
      - ../backend/usr/src/app
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    command: npm start