services:
  backend:
    image: team4-webproject-backend:latest
    restart: unless-stopped
    ports:
      - '8050:8050'
    logging:
      driver: "local"
      options:
        max-size: 10M
        max-file: 5
    networks:
      some-fancy-app:

  frontend:
    image: team4-webproject:latest
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    logging:
      driver: "local"
      options:
        max-size: 10M
        max-file: 5
    networks:
      some-fancy-app:

  networks:
    some-fancy-app: 