services:
  backend:
    image: sebassha/team4-webproject-backend:latest
    restart: unless-stopped
    ports:
      - '8094:8094'
    logging:
      driver: "local"
      options:
        max-size: 10M
        max-file: 5
    networks:
      - some-fancy-app

  frontend:
    image: sebassha/team4-webproject:latest
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - '8084:8084'
    logging:
      driver: "local"
      options:
        max-size: 10M
        max-file: 5
    networks:
      - some-fancy-app

networks:
  some-fancy-app:
